# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUri', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
